### PR TITLE
add vslam configs for mapping, localization, and nav

### PR DESCRIPTION
**Pull request by maxxlife**
Propose to add 4 new scripts to launch 3 modes.
First script to launch ros1-ros2 bridge with ease. Second script to launch VSLAM mapping.
Third script to launch VSLAM localization.
Fourth script to launch nav2 navigation.
Add subsequent tracker configs for mapping, and localization modes Add rviz config for localization-navigation mode.
Add nav2 config file for the mikrik robot.
Note that It is the first nav2 config version, not so optimized.

### CODE REVIEW

**Comment by mxlfrbt** [comment]
Let me take a look and validate your code.
Btw, thank you for your contribution into a project. Do I need to perform any additional changes in the launch files for univloc tracker, and server? Do you have more detailed documentation or how-to guide how to correctly to setup all of this?

**Comment by maxxlife** [comment]
> Let me take a look and validate your code. Btw, thank you for your contribution into a project. Do I need to perform any additional changes in the launch files for univloc tracker, and server? Do you have more detailed documentation or how-to guide how to correctly to setup all of this?

I will share a Hackster tutorial as soon as it will be ready, so you can read it, and try to set things. I've sent a draft version of the tutorial via email to you. Let me know if you was able to reproduce my Robotics SDK setup. Yesterday I validated it on two NUCs, and if works fine. Just make sure to have path to all the config files correct in all scripts, launch files, and configs. Thanks.

**Comment by mxlfrbt** [comment]
Okay, I just read your draft of the documentation. I will approve a PR after you publish it online.

**Comment by mxlfrbt** [comment]
I see your article, let's merge it. Thanks.

**Pull request merged**
